### PR TITLE
Prevent redefine rule behavior

### LINKED ISSUE #534: Stacking multiple results on the same call configuration instance doesn't work
Sorry if the title is not clear, here's an example to illustrate the problem.

I expected the two following snippets to be equivalent:

```c#
// Snippet 1
A.CallTo(() => foo.Get()).Returns(42);
A.CallTo(() => foo.Get()).Returns(100).Twice();

// Snippet 2
var call = A.CallTo(() => foo.Get());
call.Returns(42);
call.Returns(100).Twice();
```

But apparently they're not. With the first snippet, successive calls to `foo.Get()` return 100, 100, 42, 42, 42, 42 ... (as expected). But with the second snippet, successive calls to `foo.Get()` return 100, 100, 0, 0, 0, 0... The first `Returns()` is ignored; the second `Returns()` apparently overwrites the first, rather than stacking upon it.

Is this the expected behavior? If it is, it's quite confusing, and goes against the principle of least surprise. I sometimes store the result of `A.CallTo()` to avoid repeating it multiple times (usually because I want to configure the call AND verify that it happened), and I certainly didn't expect this behavior.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #534.
Closes #557, which this PR supersedes.
I just rebased @thomaslevesque's commits after I caused a conflict with #568.
All I had to do was resolve the conflicting types for `wherePredicates` in BuildableCallRule.cs.

#557's original description:

> This is in order to prevent an unsupported scenario where the user keeps
> the result of A.CallTo(...) and uses it to define multiple behaviors.
> Doing so would override the existing behavior, not stack the new one,
> even though it's not necessarily what the user would expect. Making it
> illegal prevents confusion. It remains possible to keep the result of
> A.CallTo to make later calls to MustHaveHappened and friends.
> 
> See the comments in FakeItEasy/FakeItEasy#534 for more details.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Well obviously I don't have much to say about the code :wink: 
Looks good to me :+1:
